# Generated by Django 4.0.3 on 2022-04-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymtrack',
            name='g_uid',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='GymTrack',
        ),
    ]
