# Generated by Django 4.0.3 on 2022-07-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminacc_queue_queueuser_useracc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueuser',
            old_name='shopAdmin_name',
            new_name='adminAcc_name',
        ),
        migrations.AddField(
            model_name='queueuser',
            name='adminAcc_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminAccFk_in_queueUser', to='core.adminacc'),
        ),
    ]
