# Generated by Django 4.0.3 on 2022-08-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_shopadmin_name_queueuser_adminacc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueuser',
            name='adminAcc_fk',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='queue_fk',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='userAcc_fk',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='QueueUser',
        ),
    ]
