# Generated by Django 4.0.3 on 2022-08-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_queueuser_adminacc_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('setMaxPeople', models.IntegerField(default=1000)),
                ('isOpen', models.BooleanField(default=True)),
                ('adminAcc_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminAccFk_in_queue', to='core.adminacc')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(default='no value', max_length=80)),
                ('userAcc_name', models.CharField(default='no value', max_length=80)),
                ('adminAcc_name', models.CharField(default='no value', max_length=80)),
                ('joinedTime', models.CharField(max_length=20)),
                ('adminAcc_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminAccFk_in_queueUser', to='core.adminacc')),
                ('queue_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queueFk_in_queueUser', to='core.queue')),
                ('userAcc_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAccFk_in_queueUser', to='core.useracc')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
