# Generated by Django 4.0.3 on 2022-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_queue_queueuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueuser',
            name='joinedTime',
            field=models.CharField(max_length=50),
        ),
    ]
