# Generated by Django 4.0.3 on 2022-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_queueuser_joinedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='total_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
