# Generated by Django 4.0.3 on 2022-09-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_queue_total_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='total_people',
            new_name='totalpeople',
        ),
    ]
