# Generated by Django 4.0.3 on 2022-09-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_total_people_queue_totalpeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='totalpeople',
            new_name='totalPeople',
        ),
    ]
