# Generated by Django 4.0.3 on 2022-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_totalpeople_queue_totalpeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='totalPeople',
        ),
    ]
