# Generated by Django 4.0.3 on 2022-09-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_queue_totalpeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueuser',
            name='adminAcc_name',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='queue_name',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='userAcc_name',
        ),
    ]
